config/routes.rb
Spatialability::Application.routes.draw do
  root :to => 'site#land'
  
  match '/lab/:id' => 'lab#land', :as => :lab_land
  match '/study/:study_id/finish' => 'study#finish', :as => :study_finish
  match '/study/:study_id/instrument/:instrument_id' => 'study#instrument', :as => :study_instrument
  match '/study/:study_id' => 'study#start', :as => :study_start
  
  devise_for :experimenters
  
  namespace :experimenter do
    root :to => 'site#dashboard'
    match 'shared_data', to: 'site#shared_data', as: :shared_data, via: :get
    resources :experimenters
    resources :labs
    resources :studies do
      get 'data', :on => :member
      resources :participants do
        resources :virtual_navigation_logs, :only => :show
      end
    end
  end
end

app/models/experimenter.rb
class Experimenter < ActiveRecord::Base
  belongs_to :lab
  has_many :studies
  
  devise :database_authenticatable, :recoverable, :rememberable, :trackable

  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :lab_id, :administrator, :lab_manager
  
  validates_presence_of :first_name, :last_name, :email, :lab
  validates_uniqueness_of :email
  
  def full_name
    "#{first_name} #{last_name}"
  end

  # for use by simple_form
  def name
  	full_name
  end
end

app/controllers/experimenter/experimenters_controller.rb
class Experimenter::ExperimentersController < ApplicationController
  before_filter :authenticate_experimenter!
  
  def index
    if current_experimenter.administrator
      @experimenters = Experimenter.where('')
    else
      @experimenters = current_experimenter.lab.experimenters
    end
  end
  
  def new
    @experimenter = Experimenter.new
  end
  
  def show
    @experimenter = Experimenter.find(params[:id])
  end
  
  def edit
    @experimenter = Experimenter.find(params[:id])
  end
  
  def create
    @experimenter = Experimenter.new(params[:experimenter])

    respond_to do |format|
      if @experimenter.save
        flash[:success] = "Experimenter record created for <strong>#{@experimenter.full_name}</strong>."
        format.html { redirect_to(experimenter_experimenter_url(@experimenter)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @experimenter = Experimenter.find(params[:id])

    respond_to do |format|
      if @experimenter.update_attributes(params[:experimenter])
        flash[:success] = "Experimenter record updated for <strong>#{@experimenter.full_name}</strong>."
        format.html { redirect_to(experimenter_experimenter_url(@experimenter)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @experimenter = Experimenter.find(params[:id])
    @experimenter.destroy

    respond_to do |format|
      flash[:success] = "Experimenter record deleted for <strong>#{@experimenter.full_name}</strong>."
      format.html { redirect_to(experimenter_experimenters_url) }
    end
  end
end

app/controllers/experimenter/labs_controller.rb
class Experimenter::LabsController < ApplicationController
  before_filter :authenticate_experimenter!

  def index
    @labs = Lab.all
  end
  
  def new
    @lab = Lab.new
  end
  
  def show
    @lab = Lab.find(params[:id])
  end
  
  def edit
    @lab = Lab.find(params[:id])
  end
  
  def create
    @lab = Lab.new(params[:lab])

    respond_to do |format|
      if @lab.save
        flash[:success] = "Lab record created for <strong>#{@lab.name}</strong>."
        format.html { redirect_to(experimenter_lab_url(@lab)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @lab = Lab.find(params[:id])

    respond_to do |format|
      if @lab.update_attributes(params[:lab])
        flash[:success] = "Lab record updated for <strong>#{@lab.name}</strong>."
        format.html { redirect_to(experimenter_lab_url(@lab)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @lab = Lab.find(params[:id])
    @lab.destroy

    respond_to do |format|
      flash[:success] = "Lab record deleted for <strong>#{@lab.name}</strong>."
      format.html { redirect_to(experimenter_labs_url) }
    end
  end
end

app/controllers/experimenter/participants_controller.rb
class Experimenter::ParticipantsController < ApplicationController
  before_filter :authenticate_experimenter!
  
  def index
    @study = Study.find(params[:study_id])
    @participants = @study.participants
  end
  
  def show
    @participant = Participant.find(params[:id])
  end
  
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      flash[:success] = "Participant records deleted for <strong>#{@participant.identification}</strong>."
      format.html { redirect_to(experimenter_study_url(@participant.study)) }
    end
  end
end

app/controllers/experimenter/site_controller.rb
class Experimenter::SiteController < ApplicationController
  before_filter :authenticate_experimenter!
  
  def dashboard
    if current_experimenter.administrator
      @labs = Lab.where('')
      @studies = Study.where('')
      @experimenters = Experimenter.where('')
    else
      @studies = current_experimenter.lab.studies
      @experimenters = current_experimenter.lab.experimenters
    end
  end

  def shared_data
    @participants_with_currently_shared_data = Participant.with_currently_shared_data
    
    if params[:table]
      @table = params[:table]
    else
      @table = 'spatial-ability-and-demographics'
    end
  end
end

app/controllers/experimenter/studies_controller.rb
class Experimenter::StudiesController < ApplicationController
  before_filter :authenticate_experimenter!

  def index
    if current_experimenter.administrator
      @studies = Study.where('')
    else
      @studies = current_experimenter.lab.studies
    end
  end
  
  def new
    @study = Study.new
  end
  
  def show
    @study = Study.find(params[:id])
  end

  def data
    @study = Study.find(params[:id])

    if params[:table]
      @table = params[:table]
    else
      @table = 'spatial-ability-and-demographics'
    end
  end
  
  def edit
    @study = Study.find(params[:id])
  end
  
  def create
    @study = Study.new(params[:study])

    respond_to do |format|
      if @study.save
        flash[:success] = "Study record created for <strong>#{@study.name}</strong>."
        format.html { redirect_to(experimenter_study_url(@study)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @study = Study.find(params[:id])

    respond_to do |format|
      if @study.update_attributes(params[:study])
        flash[:success] = "Study record updated for <strong>#{@study.name}</strong>."
        format.html { redirect_to(experimenter_study_url(@study)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @study = Study.find(params[:id])
    @study.destroy

    respond_to do |format|
      flash[:success] = "Study record deleted for <strong>#{@study.name}</strong>."
      format.html { redirect_to(experimenter_studies_url) }
    end
  end
end

app/controllers/experimenter/virtual_navigation_logs_controller.rb
class Experimenter::VirtualNavigationLogsController < ApplicationController
  before_filter :authenticate_experimenter!

  def show
    @virtual_navigation_log = VirtualNavigationLog.find(params[:id])
    render :text => @virtual_navigation_log.log
  end
end

app/views/experimenter/experimenters/_table.html.erb
<h2>Experimenters</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Experimenter name</th>
      <th>Lab</th>
      <th>&#35; of studies</th>
      <th>Last signed in</th>
    </tr>
  </thead>
  <% for experimenter in @experimenters %>
  <tr>
    <td><strong><%= link_to experimenter.full_name, experimenter_experimenter_path(experimenter) %></strong></td>
    <td><%= experimenter.lab.name %>
    <td><%= pluralize(experimenter.studies.length, "study") %></td>
    <td>
      <% if experimenter.last_sign_in_at %>
        <%= time_ago_in_words experimenter.last_sign_in_at %> ago
      <% else %>
        never
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/experimenter/experimenters/edit.slim
- content_for :body do
  = simple_form_for([:experimenter, @experimenter], :html => { :class => 'form-horizontal' }) do |f|
    h1 = @experimenter.full_name
    ul.nav.nav-tabs
      li
        = link_to "View", experimenter_experimenter_path(@experimenter)
      li.active
        a Edit
        
    - if f.error_messages
      = f.error_messages :class => "alert alert-error", :header_tag => :strong
    - if current_experimenter.administrator
      = f.association :lab, :as => :select, :include_blank => false
    - elsif current_experimenter.lab_manager and current_experimenter.lab == @experimenter.lab
      = f.association :lab, :as => :select, :include_blank => false, :collection => [@experimenter.lab]
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :lab_manager
    - if current_experimenter.administrator
      = f.input :administrator
          
    .form-actions
      = f.submit "Save Changes", {:class => "btn btn-primary"}

  h2 Change Password
  = simple_form_for([:experimenter, @experimenter], :html => {:class => 'form-horizontal'}) do |f|
    = f.input :password
    = f.input :password_confirmation
    .form-actions
      = f.submit "Change Password", {:class => "btn btn-primary"}

  h2 Delete Experimenter
  p Deleting this user will permanently remove all associated records.
  .form-horizontal
    .form-actions
      = button_to "Delete Experimenter", experimenter_experimenter_path(@experimenter), :method => :delete, :class => "btn btn-danger", :confirm => "Are you sure you want to delete #{@experimenter.full_name}?"

= render :template => '/experimenter/layout'

app/views/experimenter/experimenters/index.slim
- content_for :body do
  = render "table"
  
  - if current_experimenter.administrator or current_experimenter.lab_manager
    .pull-right
      = link_to "Create Experimenter", new_experimenter_experimenter_path, :class => "btn btn-primary"

= render :template => '/experimenter/layout'

app/views/experimenter/experimenters/new.slim
- content_for :body do
  = simple_form_for([:experimenter, @experimenter], :html => { :class => 'form-horizontal' }) do |f|
    h1 Create Experimenter
        
    - if f.error_messages
      = f.error_messages :class => "alert alert-error", :header_tag => :strong
    - if current_experimenter.administrator
      = f.association :lab, :as => :select, :include_blank => false
    - elsif current_experimenter.lab_manager
      = f.association :lab, :as => :select, :include_blank => false, :collection => [current_experimenter.lab]
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :password, :required => true
    = f.input :password_confirmation, :required => true
    = f.input :lab_manager
          
    .form-actions
      = f.submit "Create User", {:class => "btn btn-primary"}
      
= render :template => '/experimenter/layout'

app/views/experimenter/experimenters/show.slim
- content_for :body do
  h1 = @experimenter.full_name
  ul.nav.nav-tabs
    li.active 
      a View
    - if current_experimenter.administrator or (current_experimenter.lab_manager and current_experimenter.lab == @experimenter.lab)
      li = link_to "Edit", edit_experimenter_experimenter_path(@experimenter)

  p
    strong E-mail address:
    = @experimenter.email
  p
    strong Lab:
    = @experimenter.lab.name
  p
    strong Lab manager?
    = @experimenter.lab_manager ? 'yes' : 'no'
  p
    strong Administrator?
    = @experimenter.administrator ? 'yes' : 'no'


= render :template => '/experimenter/layout'