config/routes.rb
Spatialability::Application.routes.draw do
  root :to => 'site#land'
  
  match '/lab/:id' => 'lab#land', :as => :lab_land
  match '/study/:study_id/finish' => 'study#finish', :as => :study_finish
  match '/study/:study_id/instrument/:instrument_id' => 'study#instrument', :as => :study_instrument
  match '/study/:study_id' => 'study#start', :as => :study_start
  
  devise_for :experimenters
  
  namespace :experimenter do
    root :to => 'site#dashboard'
    match 'shared_data', to: 'site#shared_data', as: :shared_data, via: :get
    resources :experimenters
    resources :labs
    resources :studies do
      get 'data', :on => :member
      resources :participants do
        resources :virtual_navigation_logs, :only => :show
      end
    end
  end
end

app/models/experimenter.rb
class Experimenter < ActiveRecord::Base
  belongs_to :lab
  has_many :studies
  
  devise :database_authenticatable, :recoverable, :rememberable, :trackable

  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :lab_id, :administrator, :lab_manager
  
  validates_presence_of :first_name, :last_name, :email, :lab
  validates_uniqueness_of :email
  
  def full_name
    "#{first_name} #{last_name}"
  end

  # for use by simple_form
  def name
  	full_name
  end
end

app/controllers/experimenter/experimenters_controller.rb
class Experimenter::ExperimentersController < ApplicationController
  before_filter :authenticate_experimenter!
  
  def index
    if current_experimenter.administrator
      @experimenters = Experimenter.where('')
    else
      @experimenters = current_experimenter.lab.experimenters
    end
  end
  
  def new
    @experimenter = Experimenter.new
  end
  
  def show
    @experimenter = Experimenter.find(params[:id])
  end
  
  def edit
    @experimenter = Experimenter.find(params[:id])
  end
  
  def create
    @experimenter = Experimenter.new(params[:experimenter])

    respond_to do |format|
      if @experimenter.save
        flash[:success] = "Experimenter record created for <strong>#{@experimenter.full_name}</strong>."
        format.html { redirect_to(experimenter_experimenter_url(@experimenter)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @experimenter = Experimenter.find(params[:id])

    respond_to do |format|
      if @experimenter.update_attributes(params[:experimenter])
        flash[:success] = "Experimenter record updated for <strong>#{@experimenter.full_name}</strong>."
        format.html { redirect_to(experimenter_experimenter_url(@experimenter)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @experimenter = Experimenter.find(params[:id])
    @experimenter.destroy

    respond_to do |format|
      flash[:success] = "Experimenter record deleted for <strong>#{@experimenter.full_name}</strong>."
      format.html { redirect_to(experimenter_experimenters_url) }
    end
  end
end

app/controllers/experimenter/labs_controller.rb
class Experimenter::LabsController < ApplicationController
  before_filter :authenticate_experimenter!

  def index
    @labs = Lab.all
  end
  
  def new
    @lab = Lab.new
  end
  
  def show
    @lab = Lab.find(params[:id])
  end
  
  def edit
    @lab = Lab.find(params[:id])
  end
  
  def create
    @lab = Lab.new(params[:lab])

    respond_to do |format|
      if @lab.save
        flash[:success] = "Lab record created for <strong>#{@lab.name}</strong>."
        format.html { redirect_to(experimenter_lab_url(@lab)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @lab = Lab.find(params[:id])

    respond_to do |format|
      if @lab.update_attributes(params[:lab])
        flash[:success] = "Lab record updated for <strong>#{@lab.name}</strong>."
        format.html { redirect_to(experimenter_lab_url(@lab)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @lab = Lab.find(params[:id])
    @lab.destroy

    respond_to do |format|
      flash[:success] = "Lab record deleted for <strong>#{@lab.name}</strong>."
      format.html { redirect_to(experimenter_labs_url) }
    end
  end
end

app/controllers/experimenter/participants_controller.rb
class Experimenter::ParticipantsController < ApplicationController
  before_filter :authenticate_experimenter!
  
  def index
    @study = Study.find(params[:study_id])
    @participants = @study.participants
  end
  
  def show
    @participant = Participant.find(params[:id])
  end
  
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      flash[:success] = "Participant records deleted for <strong>#{@participant.identification}</strong>."
      format.html { redirect_to(experimenter_study_url(@participant.study)) }
    end
  end
end

app/controllers/experimenter/site_controller.rb
class Experimenter::SiteController < ApplicationController
  before_filter :authenticate_experimenter!
  
  def dashboard
    if current_experimenter.administrator
      @labs = Lab.where('')
      @studies = Study.where('')
      @experimenters = Experimenter.where('')
    else
      @studies = current_experimenter.lab.studies
      @experimenters = current_experimenter.lab.experimenters
    end
  end

  def shared_data
    @participants_with_currently_shared_data = Participant.with_currently_shared_data
    
    if params[:table]
      @table = params[:table]
    else
      @table = 'spatial-ability-and-demographics'
    end
  end
end

app/controllers/experimenter/studies_controller.rb
class Experimenter::StudiesController < ApplicationController
  before_filter :authenticate_experimenter!

  def index
    if current_experimenter.administrator
      @studies = Study.where('')
    else
      @studies = current_experimenter.lab.studies
    end
  end
  
  def new
    @study = Study.new
  end
  
  def show
    @study = Study.find(params[:id])
  end

  def data
    @study = Study.find(params[:id])

    if params[:table]
      @table = params[:table]
    else
      @table = 'spatial-ability-and-demographics'
    end
  end
  
  def edit
    @study = Study.find(params[:id])
  end
  
  def create
    @study = Study.new(params[:study])

    respond_to do |format|
      if @study.save
        flash[:success] = "Study record created for <strong>#{@study.name}</strong>."
        format.html { redirect_to(experimenter_study_url(@study)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @study = Study.find(params[:id])

    respond_to do |format|
      if @study.update_attributes(params[:study])
        flash[:success] = "Study record updated for <strong>#{@study.name}</strong>."
        format.html { redirect_to(experimenter_study_url(@study)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @study = Study.find(params[:id])
    @study.destroy

    respond_to do |format|
      flash[:success] = "Study record deleted for <strong>#{@study.name}</strong>."
      format.html { redirect_to(experimenter_studies_url) }
    end
  end
end

app/controllers/experimenter/virtual_navigation_logs_controller.rb
class Experimenter::VirtualNavigationLogsController < ApplicationController
  before_filter :authenticate_experimenter!

  def show
    @virtual_navigation_log = VirtualNavigationLog.find(params[:id])
    render :text => @virtual_navigation_log.log
  end
end

app/controllers/study_controller.rb
class StudyController < ApplicationController
  def start    
    @study = Study.find(params[:study_id])
    
    if request.post?
      @participant = Participant.new(params[:participant])
      @participant.study = @study
      if @study.ask_name or @study.ask_email
        ppr = ParticipantPersonalRecord.new(params[:participant_personal_record])
        ppr.save()
        @participant.participant_personal_record = ppr
      end
      
      # only for Virtual Ambler
      if params[:commit] == "Take Study with Mouse"
        cookies[:input] = "mouse"
      elsif params[:commit] == "Take Study with Joystick"
        cookies[:input] = "joystick"
      end
      
      if @participant.save() and cookies[:participant_id] = @participant.id
        redirect_to study_instrument_path({:study_id => @study.id, :instrument_id => 0})
      else
        flash[:error] = "Error starting the study. Did you complete all of the identification questions?"
      end
    else
      @participant = Participant.new
    end
  end
  
  def instrument
    # make sure the participant has actually started the study
    # otherwise send them back to the beginning
    if not cookies[:participant_id]
      return redirect_to study_start_path(params[:study_id])
    end

    @study = Study.find(params[:study_id])
    @instrument = @study.instrument_in_studies.find_by_order(params[:instrument_id])
    @participant = Participant.find(cookies[:participant_id])
    
    # SPATIAL ABILITY INSTRUMENTS
    if @instrument.instrument == "SBSOD"
      if request.post?
        sbsod = SbsodRecord.new(params[:sbsod])
        sbsod.participant = @participant
        sbsod.randomized = @instrument.randomize
        if sbsod.save()
          next_instrument(@study, @instrument.order)
        else
          flash[:error] = "Oops! We couldn't save your responses. Did you complete the entire questionnaire?"
        end
      else
        @sbsod_record = SbsodRecord.new
      end
      
    elsif @instrument.instrument == "MRT"
      if request.post?
        mrt = MrtRecord.new
        mrt.participant = @participant
        mrt.force_wait = @instrument.force_wait
        
        responses = []
         (1..20).each do |q|
          responses[q] = ""
           (1..4).each do |c|
            responses[q] << params["q#{q}_c#{c}"] if params["q#{q}_c#{c}"]
          end
          eval "mrt.q#{q} = responses[#{q}]"
        end
        
        if mrt.save()
          next_instrument(@study, @instrument.order)
        else
          flash[:error] = "Oops! We couldn't save your responses. Did you complete the entire questionnaire?"
        end
      else
        @mrt_record = MrtRecord.new
      end
      
    elsif @instrument.instrument == "VV"
      if request.post?
        vv = VvRecord.create(params[:vv_record])
        vv.participant = @participant
        
        if vv.save()
          next_instrument(@study, @instrument.order)
        else
          flash[:error] = "Oops! We couldn't save your responses. Did you complete the entire questionnaire?"
        end
      else
        @vv_record = VvRecord.new
      end
      
    elsif @instrument.instrument == "PF"
      if request.post?
        pf = PfRecord.new
        pf.participant = @participant
        pf.force_wait = @instrument.force_wait
        
        responses = []
         (1..20).each do |q|
          responses[q] = ""
          responses[q] = params["q#{q}"] if params["q#{q}"]
          eval "pf.q#{q} = responses[#{q}]"
        end
        
        if pf.save()
          next_instrument(@study, @instrument.order)
        else
          flash[:error] = "Oops! We couldn't save your responses. Did you complete the entire questionnaire?"
        end
      else
        @pf_record = PfRecord.new
      end
      
    elsif @instrument.instrument == "PVAS"
      if request.post?
        pvas = PvasRecord.new(params[:pvas])
        pvas.participant = @participant
        pvas.randomized = @instrument.randomize
        if pvas.save()
          next_instrument(@study, @instrument.order)
        else
          flash[:error] = "Oops! We couldn't save your responses. Did you complete the entire questionnaire?"
        end
      else
        @pvas_record = PvasRecord.new
      end
      
    elsif @instrument.instrument == "PSAS"
      if request.post?
        psas = PsasRecord.new(params[:psas])
        psas.participant = @participant
        psas.randomized = @instrument.randomize
        psas.length = @instrument.version
        if psas.save()
          next_instrument(@study, @instrument.order)
        else
          flash[:error] = "Oops! We couldn't save your responses. Did you complete the entire questionnaire?"
        end
      else
        @psas_record = PsasRecord.new
      end
      
      # VAMBLER INSTRUMENTS
    elsif @instrument.instrument == "Vambler Demographics"
      if request.post?
        vambler_demographics_record = VamblerDemographicsRecord.new(params[:vambler_demographics_record])
        vambler_demographics_record.participant = @participant
        if vambler_demographics_record.save()
          next_instrument(@study, @instrument.order)
        else
          flash[:error] = "Oops! We couldn't save your responses. Did you complete the entire questionnaire?"
        end
      else
        @vambler_demographics_record = VamblerDemographicsRecord.new
      end
    
    elsif @instrument.instrument == "Silcton Free Exploration"
      @virtual_environment = VirtualEnvironment.find_by_name("Ambler")
      if request.post?
        if params[:virtual_navigation_log].present? &&
           params[:virtual_navigation_log][:log].present?
          VirtualNavigationLog.create(
            :participant => @participant, 
            :virtual_environment => @virtual_environment,
            :log => params[:virtual_navigation_log][:log],
            :route => @instrument.instrument
          )
        end
        next_instrument(@study, @instrument.order)
      end

    elsif @instrument.instrument == "Vambler Route Learning"
      # GET
      @virtual_environment = VirtualEnvironment.find_by_name("Ambler")
      
      if @instrument.version == "Main Routes"
        # if this is the first main route learning
        if @participant.vambler_main_routes_order.nil?
          if @study.participants.count(:conditions => "vambler_main_routes_order = 'AB'") > @study.participants.count(:conditions => "vambler_main_routes_order = 'BA'")
            @participant.vambler_main_routes_order = "BA"
            @participant.save()
            @route = "B"
            @route_order = "first"
          else
            @participant.vambler_main_routes_order = "AB"
            @participant.save()
            @route = "A"
            @route_order = "first"
          end
          # or if this is the second main route learning  
        elsif @participant.vambler_main_routes_order == "AB"
          @route = "B"
          @route_order = "second"
        elsif @participant.vambler_main_routes_order == "BA"
          @route = "A"
          @route_order = "second"
        end
      elsif @instrument.version == "Connector Routes"
        # if this is the first connector route learning
        if @participant.vambler_connector_routes_order.nil?
          if @study.participants.count(:conditions => "vambler_connector_routes_order = '12'") > @study.participants.count(:conditions => "vambler_connector_routes_order = '21'")
            @participant.vambler_connector_routes_order = "21"
            @participant.save()
            @route = "C2"
            @route_order = "first"
          else
            @participant.vambler_connector_routes_order = "12"
            @participant.save()
            @route = "C1"
            @route_order = "first"
          end
          # or if this is the second connector route learning  
        elsif @participant.vambler_connector_routes_order == "12"
          @route = "C2"
          @route_order = "second"
        elsif @participant.vambler_connector_routes_order == "21"
          @route = "C1"
          @route_order = "second"
        end
      end
      # POST
      if request.post?
        if params[:virtual_navigation_log].present? &&
           params[:virtual_navigation_log][:log].present? &&
           params[:virtual_navigation_log][:route].present?
          VirtualNavigationLog.create(
            :participant => @participant, 
            :virtual_environment => @virtual_environment,
            :log => params[:virtual_navigation_log][:log],
            :route => params[:virtual_navigation_log][:route]
          )
        end
        next_instrument(@study, @instrument.order)
      end
    elsif @instrument.instrument == "Vambler On-site Pointing"
      @virtual_environment = VirtualEnvironment.find_by_name("Ambler")
      
      if request.post?
        @virtual_direction_test = VirtualDirectionTest.new
        @virtual_direction_test.participant = @participant
        @virtual_direction_test.virtual_environment = @virtual_environment
        @virtual_direction_test.style = "onsite"
        
        total_direction_estimates = params["total_direction_estimates"]
        (0 .. Integer(total_direction_estimates)).each do |i|
          virtual_direction_estimate = VirtualDirectionEstimate.new
          virtual_direction_estimate.virtual_direction_test = @virtual_direction_test
          virtual_direction_estimate.start_landmark = VirtualLandmark.find(params[:virtual_direction_estimates]["#{i}"][:start_landmark_id])
          virtual_direction_estimate.facing_landmark = VirtualLandmark.find(params[:virtual_direction_estimates]["#{i}"][:facing_landmark_id])

app/views/experimenter/studies/_table.html.erb
<% if current_experimenter.administrator %>
<h2>All Studies</h2>
<% else %>
<h2><%= current_experimenter.lab.name %> Studies</h2>
<% end %>

<table class="table table-striped">
  <thead>
    <th>Study Name</th>
    <th>Active?</th>
    <th>Last administered</th>
    <th>&#35; of participants</th>
    <th>When to share data</th>
    <th>&#35; of participants currently shared</th>
    <th>Primary experimenter</th>
  </thead>
  <% for study in @studies %>
  <tr>
    <td><strong><%= link_to study.name, experimenter_study_path(study) %></strong></td>
    <td><% if study.active %><img src="/images/icon-lightbulb.png" alt="Active"/><% end %></td>
    <td>
      <% if study.last_administered %>
        <%= time_ago_in_words study.last_administered %> ago
      <% else %>
        never
      <% end %>
    </td>
    <td><%= pluralize(study.participants.count, "participant")%></td>
    <td><%= study.when_to_share_data %></td>
    <td>
      <%- if study.participants.with_currently_shared_data.count > 0 %>
        <%= pluralize(study.participants.with_currently_shared_data.count, "participant")%>
      <%- end %>
    </td>
    <td><%= link_to study.experimenter.full_name, experimenter_experimenter_path(study.experimenter) %>
  </tr>
  <% end %>
</table>

app/views/experimenter/studies/edit.slim
- content_for :head do
  = javascript_include_tag "/javascripts/jquery-ui-1.8.custom.min.js"
  = javascript_include_tag "study-create-edit-form"

- content_for :body do
  = simple_form_for([:experimenter, @study], :html => { :class => 'form-horizontal' }) do |f|
    h1 = @study.name
    ul.nav.nav-tabs
      li
        = link_to "View Study", experimenter_study_path(@study)
      li.active 
        a Edit Study
        
    - if f.error_messages
      = f.error_messages :class => "alert alert-error", :header_tag => :strong
    = f.input :name
    = f.association :experimenter, :as => :select, :label => 'Primary experimenter', :collection => @study.lab.experimenters, :include_blank => false
    = f.input :active
    = f.input :ask_participant_id, :label => 'Ask for participant ID?'

    h2 When to Share Data
    = f.select :when_to_share_data, [['Immediately', 'immediately'], ['After 3 Years', '3years']]

    h2 Start Button(s)
    = f.input :kind_of_start_buttons, :as => :select, :collection => [['Standard', "standard"], ['Virtual SILCton ("Mouse" and "Joystick")', "vambler"]], :include_blank => false

    h2 Instruments
    p#add-another-instrument
      ' Add another instrument: 
      select#instrument-to-add-select
        option Virtual SILCton Demographics Questionnaire
        option SBSOD (fixed order)
        option PSAS (short version, randomized)
        option PSAS (long version, randomized)
        option PVAS (randomized)
        option MRT (forced wait)
        option Virtual SILCton Route Learning (Main Routes)
        option Virtual SILCton Route Learning (Connector Routes)
        option Virtual SILCton Free Exploration
        option Virtual SILCton On-site Pointing
        option Virtual SILCton Off-site Pointing
        option Virtual SILCton Distance Estimates
        option Virtual SILCton Map Arrangements
      ' 
      a.btn.btn-primary#add-button Add
    p Drag rows up and down to reorder the instruments.
    table.table#instruments-in-study-table
      thead
        tr
          th Order
          th Instrument
          th Version
          th Randomize?
        tbody
          = f.fields_for :instrument_in_studies do |iis|
            tr
              td
                span.order = iis.object.order + 1
                = iis.input :order, :as => :hidden, :input_html => {:class => 'order-field'}
              td
                = iis.object.instrument
                = iis.input :instrument, :as => :hidden
              td 
                = iis.object.version
                = iis.input :version, :as => :hidden
              td 
                = iis.object.randomize ? 'yes' : ''
                = iis.input :randomize, :as => :hidden
              td
                a.btn.btn-danger.remove-button Remove
                = iis.hidden_field :_destroy, :class => 'destroy-field'

    h2 Instructions
    = f.input :welcome_text, :input_html => {:class => 'span6'}
    = f.input :completion_text, :input_html => {:class => 'span6'}

    .form-actions
      = link_to "Cancel", experimenter_study_path(@study), {:class => "btn", :style => 'margin-right: 10px;'}
      = f.submit "Save Study", {:class => "btn btn-primary"}

  h2 Delete Study
  p Deleting this study will permanently remove all associated participant records.
  .form-horizontal
    .form-actions
      = button_to "Delete Study", experimenter_study_path(@study), :method => :delete, :class => "btn btn-danger", :confirm => "Are you sure you want to delete #{@study.name}?"
      
= render :template => '/experimenter/layout'

app/views/experimenter/studies/index.slim
- content_for :body do
  = render "table"
  - if current_experimenter.administrator or current_experimenter.lab_manager
    .pull-right
      = link_to "Create Study", new_experimenter_study_path, :class => "btn btn-primary"
= render :template => '/experimenter/layout'

app/views/experimenter/studies/new.slim
- content_for :head do
  = javascript_include_tag "/javascripts/jquery-ui-1.8.custom.min.js"
  = javascript_include_tag "study-create-edit-form"

- content_for :body do
  = simple_form_for([:experimenter, @study], :html => { :class => 'form-horizontal' }) do |f|
    h1 New Study
        
    - if f.error_messages
      = f.error_messages :class => "alert alert-error", :header_tag => :strong
    = f.input :name
    - if current_experimenter.administrator
      = f.association :lab, :as => :select, :include_blank => false
      = f.association :experimenter, :as => :select, :label => 'Primary experimenter', :collection => Experimenter.all, :include_blank => false
    - else
      = f.association :lab, :as => :select, :include_blank => false, :collection => [current_experimenter.lab]
      = f.association :experimenter, :as => :select, :label => 'Primary experimenter', :collection => current_experimenter.lab.experimenters, :include_blank => false
    = f.input :active, :label => 'Active?'
    = f.input :ask_participant_id, :label => "Ask for participant ID?"

    h2 When to Share Data
    = f.select :when_to_share_data, [['Immediately', 'immediately'], ['After 3 Years', '3years']]

    h2 Start Button(s)
    = f.input :kind_of_start_buttons, :as => :select, :collection => [['Standard', "standard"], ['Virtual SILCton ("Mouse" and "Joystick")', "vambler"]], :default => "standard"

    h2 Instruments
    p#add-another-instrument
      ' Add another instrument: 
      select#instrument-to-add-select
        option Virtual SILCton Consent Form
        option Virtual SILCton Demographics Questionnaire
        option SBSOD (fixed order)
        option PSAS (short version, randomized)
        option PSAS (long version, randomized)
        option PVAS (randomized)
        option MRT (forced wait)
        option Virtual SILCton Route Learning (Main Routes)
        option Virtual SILCton Route Learning (Connector Routes)
        option Virtual SILCton Free Exploration
        option Virtual SILCton On-site Pointing
        option Virtual SILCton Off-site Pointing
        option Virtual SILCton Distance Estimates
        option Virtual SILCton Map Arrangements
      ' 
      a.btn.btn-primary#add-button Add
    p Drag rows up and down to reorder the instruments.
    table.table#instruments-in-study-table
      thead
        tr
          th Order
          th Instrument
          th Version
          th Randomize?
        tbody
          = f.fields_for :instrument_in_studies do |iis|
            tr
              td
                span.order = iis.object.order + 1
                = iis.input :order, :as => :hidden, :input_html => {:class => 'order-field'}
              td 
                = iis.object.instrument
                = iis.input :instrument, :as => :hidden
              td 
                = iis.object.version
                = iis.input :version, :as => :hidden
              td 
                = iis.object.randomize ? 'yes' : ''
                = iis.input :randomize, :as => :hidden
              td
                a.btn.btn-danger.remove-button Remove
                = iis.hidden_field :_destroy, :class => 'destroy-field'

    h2 Instructions
    = f.input :welcome_text, :input_html => {:class => 'span6'}
    = f.input :completion_text, :input_html => {:class => 'span6'}
          
    .form-actions
      = link_to "Cancel", experimenter_studies_path, {:class => "btn", :style => 'margin-right: 10px;'}
      = f.submit "Save Study", {:class => "btn btn-primary"}
      
= render :template => '/experimenter/layout'

app/views/experimenter/studies/show.slim
- content_for :head do
  = javascript_include_tag "render-data-table"

- content_for :body do
  h1 = @study.name
  ul.nav.nav-tabs
    li.active 
      a href="#view" data-toggle="tab" View Study
    - if current_experimenter == @study.experimenter or current_experimenter.lab_manager or current_experimenter.administrator
      li
        = link_to "Edit Study", edit_experimenter_study_path(@study)
    li
      a href="#participants" data-toggle="tab" View Participants
    li
      = link_to "View Data", data_experimenter_study_path(@study)

  .tab-content
    .tab-pane.active#settings
      p
        strong Active?
        - if @study.active
          span style="color: green;" Yes, currently active.
        - else
          span style="color: red;" Not currently active.

      p 
        strong URL for participants: 
        = link_to study_start_url(@study), study_start_url(@study)

      p
        strong Participant identification:
        ul
          - if @study.ask_participant_id
            li Ask for ID (can be any number or characters)
          - if @study.ask_name
            li Ask for name (first and last)
          - if @study.ask_email
            li Ask for e-mail address
          - if @study.ask_age
            li Ask for age
          - if @study.ask_sex
            li Ask for sex

      p
        strong When to share data: 
        = @study.when_to_share_data

      p
        strong Start button(s):
        - if @study.kind_of_start_buttons == 'vambler'
          | Virtual SILCton ("Mouse" and "Joystick")
        - else
          | Standard

      h2 Instruments
      table.table.table-striped
        thead
          tr
            th Order
            th Instrument Name
            th Version
        tbody
          - for instrument in @study.instrument_in_studies
            tr
              td = instrument.order + 1
              td
                - if instrument.instrument == 'Static Page'
                  = instrument.static_page.name
                - else 
                  = instrument.instrument
              td = instrument.version

      h2 Instructions
      p
        strong Welcome text: 
        == @study.welcome_text
      p
        strong Completion text: 
        == @study.completion_text

    .tab-pane#participants
      table.table.table-striped.data-table
        thead
          tr
            th Participant Identification
            th Elected to share data?
            th Age
            th Sex
            th First Name
            th Last Name
            th E-mail
            th Date
            - if current_experimenter == @study.experimenter or current_experimenter.lab_manager or current_experimenter.administrator
              th Actions
        tbody
          - for p in @study.participants
            tr
              td = p.identification
              td = p.share_data ? 'yes' : 'no'
              td = p.age
              td = p.sex
              td = p.participant_personal_record.first_name if p.participant_personal_record
              td = p.participant_personal_record.last_name if p.participant_personal_record
              td = p.participant_personal_record.email if p.participant_personal_record
              td = p.created_at
              - if current_experimenter == @study.experimenter or current_experimenter.lab_manager or current_experimenter.administrator
                td= button_to "Delete", experimenter_study_participant_path(p.study, p), :method => :delete, :class => "btn btn-danger", :confirm => "Are you sure you want to delete the records for #{p.identification}?"

= render :template => '/experimenter/layout'