config/routes.rb
Spatialability::Application.routes.draw do
  root :to => 'site#land'
  
  match '/lab/:id' => 'lab#land', :as => :lab_land
  match '/study/:study_id/finish' => 'study#finish', :as => :study_finish
  match '/study/:study_id/instrument/:instrument_id' => 'study#instrument', :as => :study_instrument
  match '/study/:study_id' => 'study#start', :as => :study_start
  
  devise_for :experimenters
  
  namespace :experimenter do
    root :to => 'site#dashboard'
    match 'shared_data', to: 'site#shared_data', as: :shared_data, via: :get
    resources :experimenters
    resources :labs
    resources :studies do
      get 'data', :on => :member
      resources :participants do
        resources :virtual_navigation_logs, :only => :show
      end
    end
  end
end

app/models/experimenter.rb
class Experimenter < ActiveRecord::Base
  belongs_to :lab
  has_many :studies
  
  devise :database_authenticatable, :recoverable, :rememberable, :trackable

  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :lab_id, :administrator, :lab_manager
  
  validates_presence_of :first_name, :last_name, :email, :lab
  validates_uniqueness_of :email
  
  def full_name
    "#{first_name} #{last_name}"
  end

  # for use by simple_form
  def name
  	full_name
  end
end

app/models/lab.rb
class Lab < ActiveRecord::Base
  has_many :experimenters, :dependent => :destroy
  has_many :studies, :dependent => :destroy
  
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/experimenter/experimenters_controller.rb
class Experimenter::ExperimentersController < ApplicationController
  before_filter :authenticate_experimenter!
  
  def index
    if current_experimenter.administrator
      @experimenters = Experimenter.where('')
    else
      @experimenters = current_experimenter.lab.experimenters
    end
  end
  
  def new
    @experimenter = Experimenter.new
  end
  
  def show
    @experimenter = Experimenter.find(params[:id])
  end
  
  def edit
    @experimenter = Experimenter.find(params[:id])
  end
  
  def create
    @experimenter = Experimenter.new(params[:experimenter])

    respond_to do |format|
      if @experimenter.save
        flash[:success] = "Experimenter record created for <strong>#{@experimenter.full_name}</strong>."
        format.html { redirect_to(experimenter_experimenter_url(@experimenter)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @experimenter = Experimenter.find(params[:id])

    respond_to do |format|
      if @experimenter.update_attributes(params[:experimenter])
        flash[:success] = "Experimenter record updated for <strong>#{@experimenter.full_name}</strong>."
        format.html { redirect_to(experimenter_experimenter_url(@experimenter)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @experimenter = Experimenter.find(params[:id])
    @experimenter.destroy

    respond_to do |format|
      flash[:success] = "Experimenter record deleted for <strong>#{@experimenter.full_name}</strong>."
      format.html { redirect_to(experimenter_experimenters_url) }
    end
  end
end

app/controllers/experimenter/labs_controller.rb
class Experimenter::LabsController < ApplicationController
  before_filter :authenticate_experimenter!

  def index
    @labs = Lab.all
  end
  
  def new
    @lab = Lab.new
  end
  
  def show
    @lab = Lab.find(params[:id])
  end
  
  def edit
    @lab = Lab.find(params[:id])
  end
  
  def create
    @lab = Lab.new(params[:lab])

    respond_to do |format|
      if @lab.save
        flash[:success] = "Lab record created for <strong>#{@lab.name}</strong>."
        format.html { redirect_to(experimenter_lab_url(@lab)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @lab = Lab.find(params[:id])

    respond_to do |format|
      if @lab.update_attributes(params[:lab])
        flash[:success] = "Lab record updated for <strong>#{@lab.name}</strong>."
        format.html { redirect_to(experimenter_lab_url(@lab)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @lab = Lab.find(params[:id])
    @lab.destroy

    respond_to do |format|
      flash[:success] = "Lab record deleted for <strong>#{@lab.name}</strong>."
      format.html { redirect_to(experimenter_labs_url) }
    end
  end
end

app/controllers/experimenter/participants_controller.rb
class Experimenter::ParticipantsController < ApplicationController
  before_filter :authenticate_experimenter!
  
  def index
    @study = Study.find(params[:study_id])
    @participants = @study.participants
  end
  
  def show
    @participant = Participant.find(params[:id])
  end
  
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      flash[:success] = "Participant records deleted for <strong>#{@participant.identification}</strong>."
      format.html { redirect_to(experimenter_study_url(@participant.study)) }
    end
  end
end

app/controllers/experimenter/site_controller.rb
class Experimenter::SiteController < ApplicationController
  before_filter :authenticate_experimenter!
  
  def dashboard
    if current_experimenter.administrator
      @labs = Lab.where('')
      @studies = Study.where('')
      @experimenters = Experimenter.where('')
    else
      @studies = current_experimenter.lab.studies
      @experimenters = current_experimenter.lab.experimenters
    end
  end

  def shared_data
    @participants_with_currently_shared_data = Participant.with_currently_shared_data
    
    if params[:table]
      @table = params[:table]
    else
      @table = 'spatial-ability-and-demographics'
    end
  end
end

app/controllers/experimenter/studies_controller.rb
class Experimenter::StudiesController < ApplicationController
  before_filter :authenticate_experimenter!

  def index
    if current_experimenter.administrator
      @studies = Study.where('')
    else
      @studies = current_experimenter.lab.studies
    end
  end
  
  def new
    @study = Study.new
  end
  
  def show
    @study = Study.find(params[:id])
  end

  def data
    @study = Study.find(params[:id])

    if params[:table]
      @table = params[:table]
    else
      @table = 'spatial-ability-and-demographics'
    end
  end
  
  def edit
    @study = Study.find(params[:id])
  end
  
  def create
    @study = Study.new(params[:study])

    respond_to do |format|
      if @study.save
        flash[:success] = "Study record created for <strong>#{@study.name}</strong>."
        format.html { redirect_to(experimenter_study_url(@study)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @study = Study.find(params[:id])

    respond_to do |format|
      if @study.update_attributes(params[:study])
        flash[:success] = "Study record updated for <strong>#{@study.name}</strong>."
        format.html { redirect_to(experimenter_study_url(@study)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @study = Study.find(params[:id])
    @study.destroy

    respond_to do |format|
      flash[:success] = "Study record deleted for <strong>#{@study.name}</strong>."
      format.html { redirect_to(experimenter_studies_url) }
    end
  end
end

app/controllers/experimenter/virtual_navigation_logs_controller.rb
class Experimenter::VirtualNavigationLogsController < ApplicationController
  before_filter :authenticate_experimenter!

  def show
    @virtual_navigation_log = VirtualNavigationLog.find(params[:id])
    render :text => @virtual_navigation_log.log
  end
end

app/controllers/lab_controller.rb
class LabController < ApplicationController
  def land
    @lab = Lab.find(params[:id])
  end
end

app/views/experimenter/labs/_table.html.erb
<h2>Labs</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Lab name</th>
      <th>&#35; of experimenters</th>
      <th>&#35; of studies</th>
    </tr>
  </thead>
  <% for lab in @labs %>
  <tr>
    <td><strong><%= link_to lab.name, experimenter_lab_path(lab) %></strong></td>
    <td><%= pluralize(lab.experimenters.length, "study") %></td>
    <td><%= pluralize(lab.studies.length, "study") %></td>
  </tr>
  <% end %>
</table>

app/views/experimenter/labs/edit.slim
- content_for :body do
  = simple_form_for([:experimenter, @lab], :html => { :class => 'form-horizontal' }) do |f|
    h1 = @lab.name
    ul.nav.nav-tabs
      li
        = link_to "View", experimenter_lab_path(@lab)
      li.active
        a Edit
        
    - if f.error_messages
      = f.error_messages :class => "alert alert-error", :header_tag => :strong
    = f.input :name
    = f.input :web_site
    = f.input :country
          
    .form-actions
      = f.submit "Save Changes", {:class => "btn btn-primary"}

  h2 Delete Lab
  p Deleting this lab will permanently remove all associated studies and experimenters.
  .form-horizontal
    .form-actions
      = button_to "Delete Lab", experimenter_lab_path(@lab), :method => :delete, :class => "btn btn-danger", :confirm => "Are you sure you want to delete #{@lab.name}?"

= render :template => '/experimenter/layout'

app/views/experimenter/labs/index.slim
- content_for :body do
  = render "table"
  
  - if current_experimenter.administrator
    .pull-right
      = link_to "Create Lab", new_experimenter_lab_path, :class => "btn btn-primary"

= render :template => '/experimenter/layout'

app/views/experimenter/labs/new.slim
- content_for :body do
  = simple_form_for([:experimenter, @lab], :html => { :class => 'form-horizontal' }) do |f|
    h1 Create Lab
        
    - if f.error_messages
      = f.error_messages :class => "alert alert-error", :header_tag => :strong
    = f.input :name
    = f.input :web_site
    = f.input :country
          
    .form-actions
      = f.submit "Create Lab", {:class => "btn btn-primary"}
      
= render :template => '/experimenter/layout'

app/views/experimenter/labs/show.slim
- content_for :body do
  h1 = @lab.name
  ul.nav.nav-tabs
    li.active 
      a View
    - if current_experimenter.administrator
      li = link_to "Edit", edit_experimenter_lab_path(@lab)
  p
  	strong Web site:
  	= link_to @lab.web_site, @lab.web_site
  p
    strong Country:
    = @lab.country

= render :template => '/experimenter/layout'