config/routes.rb
Spatialability::Application.routes.draw do
  root :to => 'site#land'
  
  match '/lab/:id' => 'lab#land', :as => :lab_land
  match '/study/:study_id/finish' => 'study#finish', :as => :study_finish
  match '/study/:study_id/instrument/:instrument_id' => 'study#instrument', :as => :study_instrument
  match '/study/:study_id' => 'study#start', :as => :study_start
  
  devise_for :experimenters
  
  namespace :experimenter do
    root :to => 'site#dashboard'
    match 'shared_data', to: 'site#shared_data', as: :shared_data, via: :get
    resources :experimenters
    resources :labs
    resources :studies do
      get 'data', :on => :member
      resources :participants do
        resources :virtual_navigation_logs, :only => :show
      end
    end
  end
end

app/models/experimenter.rb
class Experimenter < ActiveRecord::Base
  belongs_to :lab
  has_many :studies
  
  devise :database_authenticatable, :recoverable, :rememberable, :trackable

  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :lab_id, :administrator, :lab_manager
  
  validates_presence_of :first_name, :last_name, :email, :lab
  validates_uniqueness_of :email
  
  def full_name
    "#{first_name} #{last_name}"
  end

  # for use by simple_form
  def name
  	full_name
  end
end

app/controllers/experimenter/experimenters_controller.rb
class Experimenter::ExperimentersController < ApplicationController
  before_filter :authenticate_experimenter!
  
  def index
    if current_experimenter.administrator
      @experimenters = Experimenter.where('')
    else
      @experimenters = current_experimenter.lab.experimenters
    end
  end
  
  def new
    @experimenter = Experimenter.new
  end
  
  def show
    @experimenter = Experimenter.find(params[:id])
  end
  
  def edit
    @experimenter = Experimenter.find(params[:id])
  end
  
  def create
    @experimenter = Experimenter.new(params[:experimenter])

    respond_to do |format|
      if @experimenter.save
        flash[:success] = "Experimenter record created for <strong>#{@experimenter.full_name}</strong>."
        format.html { redirect_to(experimenter_experimenter_url(@experimenter)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @experimenter = Experimenter.find(params[:id])

    respond_to do |format|
      if @experimenter.update_attributes(params[:experimenter])
        flash[:success] = "Experimenter record updated for <strong>#{@experimenter.full_name}</strong>."
        format.html { redirect_to(experimenter_experimenter_url(@experimenter)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @experimenter = Experimenter.find(params[:id])
    @experimenter.destroy

    respond_to do |format|
      flash[:success] = "Experimenter record deleted for <strong>#{@experimenter.full_name}</strong>."
      format.html { redirect_to(experimenter_experimenters_url) }
    end
  end
end

app/controllers/experimenter/labs_controller.rb
class Experimenter::LabsController < ApplicationController
  before_filter :authenticate_experimenter!

  def index
    @labs = Lab.all
  end
  
  def new
    @lab = Lab.new
  end
  
  def show
    @lab = Lab.find(params[:id])
  end
  
  def edit
    @lab = Lab.find(params[:id])
  end
  
  def create
    @lab = Lab.new(params[:lab])

    respond_to do |format|
      if @lab.save
        flash[:success] = "Lab record created for <strong>#{@lab.name}</strong>."
        format.html { redirect_to(experimenter_lab_url(@lab)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @lab = Lab.find(params[:id])

    respond_to do |format|
      if @lab.update_attributes(params[:lab])
        flash[:success] = "Lab record updated for <strong>#{@lab.name}</strong>."
        format.html { redirect_to(experimenter_lab_url(@lab)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @lab = Lab.find(params[:id])
    @lab.destroy

    respond_to do |format|
      flash[:success] = "Lab record deleted for <strong>#{@lab.name}</strong>."
      format.html { redirect_to(experimenter_labs_url) }
    end
  end
end

app/controllers/experimenter/participants_controller.rb
class Experimenter::ParticipantsController < ApplicationController
  before_filter :authenticate_experimenter!
  
  def index
    @study = Study.find(params[:study_id])
    @participants = @study.participants
  end
  
  def show
    @participant = Participant.find(params[:id])
  end
  
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      flash[:success] = "Participant records deleted for <strong>#{@participant.identification}</strong>."
      format.html { redirect_to(experimenter_study_url(@participant.study)) }
    end
  end
end

app/controllers/experimenter/site_controller.rb
class Experimenter::SiteController < ApplicationController
  before_filter :authenticate_experimenter!
  
  def dashboard
    if current_experimenter.administrator
      @labs = Lab.where('')
      @studies = Study.where('')
      @experimenters = Experimenter.where('')
    else
      @studies = current_experimenter.lab.studies
      @experimenters = current_experimenter.lab.experimenters
    end
  end

  def shared_data
    @participants_with_currently_shared_data = Participant.with_currently_shared_data
    
    if params[:table]
      @table = params[:table]
    else
      @table = 'spatial-ability-and-demographics'
    end
  end
end

app/controllers/experimenter/studies_controller.rb
class Experimenter::StudiesController < ApplicationController
  before_filter :authenticate_experimenter!

  def index
    if current_experimenter.administrator
      @studies = Study.where('')
    else
      @studies = current_experimenter.lab.studies
    end
  end
  
  def new
    @study = Study.new
  end
  
  def show
    @study = Study.find(params[:id])
  end

  def data
    @study = Study.find(params[:id])

    if params[:table]
      @table = params[:table]
    else
      @table = 'spatial-ability-and-demographics'
    end
  end
  
  def edit
    @study = Study.find(params[:id])
  end
  
  def create
    @study = Study.new(params[:study])

    respond_to do |format|
      if @study.save
        flash[:success] = "Study record created for <strong>#{@study.name}</strong>."
        format.html { redirect_to(experimenter_study_url(@study)) }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def update
    @study = Study.find(params[:id])

    respond_to do |format|
      if @study.update_attributes(params[:study])
        flash[:success] = "Study record updated for <strong>#{@study.name}</strong>."
        format.html { redirect_to(experimenter_study_url(@study)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  def destroy
    @study = Study.find(params[:id])
    @study.destroy

    respond_to do |format|
      flash[:success] = "Study record deleted for <strong>#{@study.name}</strong>."
      format.html { redirect_to(experimenter_studies_url) }
    end
  end
end

app/controllers/experimenter/virtual_navigation_logs_controller.rb
class Experimenter::VirtualNavigationLogsController < ApplicationController
  before_filter :authenticate_experimenter!

  def show
    @virtual_navigation_log = VirtualNavigationLog.find(params[:id])
    render :text => @virtual_navigation_log.log
  end
end

app/views/experimenter/layout.slim
doctype html
html
  head
    title Virtual SILCton Experimenter Interface
    = stylesheet_link_tag "experimenter"
    = javascript_include_tag "experimenter"
    = csrf_meta_tags
    == yield(:head)
  body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          h3
            = link_to "Virtual SILCton Experimenter Interface", experimenter_root_path, :class => "brand"
          ul.nav
            - if current_experimenter.administrator
              li class={"active" if current_page?(experimenter_labs_path)} 
                = link_to "Labs", experimenter_labs_path
            li class={"active" if current_page?(experimenter_studies_path)} 
              = link_to "Studies", experimenter_studies_path
            li class={"active" if current_page?(experimenter_experimenters_path)} 
              = link_to "Experimenters", experimenter_experimenters_path
            li class={"active" if current_page?(experimenter_shared_data_path)} 
              = link_to "Shared Data", experimenter_shared_data_path
          ul.nav.pull-right
            li.dropdown
              a.dropdown-toggle data-toggle="dropdown"
                == "<strong>#{current_experimenter.full_name}</strong>"
                | <b class="caret"></b>
              ul.dropdown-menu
                li = link_to "Sign Out", destroy_experimenter_session_path, :method => :delete
    .container style="padding-top: 60px;"
      .section
      - if flash[:success]
        .alert.alert-success.fade.in(data-alert="alert")
          == flash[:success]
      - if flash[:info]
        .alert.alert-info.fade.in(data-alert="alert")
          == flash[:info]
      - if flash[:error]
        .alert.alert-error.fade.in(data-alert="alert")
          == flash[:error]
      - if flash[:warning]
        .alert.fade.in(data-alert="alert")
          == flash[:warning]
      == yield(:body)
    == yield(:after_container_body)